language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: IFvaqDxqOPOB1oNPBY+4RK789pISuTRJviu/Br+RbsR+rKXdiEeKyk9uZE4ig95amjxT7RshO4YogetNuDEPQxsgEvXzWuXSM2YypqbOSH0ZB5XMvNnGg4Lx+23H6Q+sjGGrNzK7vgORvQxToSQqtQ4tBqOnLy4ZCW0sVkpWdvzdgAU0TcmT2UNRlHLkL0F02IvGRS/XGwzRFmxUfGwsnxSBuxK+A6YyEcn7A/Ep14YrK++kUUjw/Z7BU8XK+C4ql0WZTAAvV6VxQfcXJW34Mg1Jz7nmEKM7Cr0zXDPwVjZ6tH+HTNoDUGIoHyA/faLX3YZEWByqcD1zkP9KHbGmXE3Drbg0iVZe7OkLpMegUGc1jHl0LWa2waQfmSiM1Z/1LhKWnv7UFzZtlC3I6Xh49cwTo0cX6Ceet+qMQzRBf72Q0RCwwNLLfqspsKyocq6Q6yUMEXFyB07pGA5GLmrpNDwfrVmPizKIeDf7LD3sTBPn10kpyFDvOt+pll4ajymW7nMgl7svzpjHa88teTVErpefsNnL1sl2Tuf8mFIMxhxDL3RnY9K45f1BcalwLuj1UDkTuNKeEmA3ry7syre3gi2iR6FX1JUxPBNPt9JRspbem8nQV8r8p2NEcrdNBCutoq5FGm1D+Hxc/H98Ja3OJR6bDLdimnYs0iBvdMOPdpE=
  - secure: nQqS9c55WLc1+NmKJ8/FbpmaKzGeKNIb5mm9RFWrWFfJzd6ImpL9itVMPMniZiLmWthqz2SCbkYKu2Vd9hPttUYomGQUH9wF85AY8BEe1WtkZcZSiZbPmbGkJOn6jXQY6TkKOrrIorxproGQCuJcFzgtnUwpVqJ3Vl2Tc+c0utScmX1SwlM1cwB9Zb5w8SwluAmm3d3yMa1vKhhFFJwB3KS02L2SDnmo5H0kWYYOhkd+jq0Cd0Bl+6adXnMmdeAd9Pc5bv+1O5LKdAS9z/H3+yZoOTYQe+wV7O/zqe34Klt7W08P6bmor5FzhFPQyPukUFQH5B/71wk2D+/XDjHayoSfColn+JfQ9CynQF7XtZJ01JNvH8bLHjWJzvC1sSvY1Tl23yZ+Jnh9oFmAaRnAWXn0IhTT2WkFQP/5QJBHSTF82FCF5p4d9nab7/xPliF5vAy4KcNVW78UP+F3fOBhBXXmiMllcTo6p+bf/qAg1WvP/3gPouyH85uAA7QpHJNrIjqwdHkC7kDPk+gd1YReidkWrPE1m9a/paClC2a7+vRoncfCKSRXinPS5o0T7iVlkqzoesRwz8Snkdb9dbWpwmIt2k0TeEaTGSO5MtYC3z0I94cjIC4VP0C2930fZzCiuP4SD97W8ronXaG4EvmIkpMu2up6UTUATj43ovFe/CU=
